/** @typedef {{ name: string, hints: string[], strengths: string[] }} TargetUni */

const ML = ['AI', 'machine learning', 'deep learning', 'data analytics', 'computer science'];
const VISION = ['vision', 'computer vision', 'multimodal'];
const MED = ['medical imaging', 'health informatics', 'biomedical'];
const ENERGY = ['forecasting', 'time-series', 'predictive analytics', 'energy'];
const NLP = ['NLP', 'natural language processing'];

/** Compact builder — all schools have CS/ML; extras tag major-relevant professor areas. */
function u(name, hints, extra = []) {
  return { name, hints, strengths: [...ML, ...extra] };
}

/** 110+ US research universities with CS / AI / analytics programs aligned to outreach majors. */
export const USA_TARGET_UNIVERSITIES = [
  u('Stanford University', ['stanford'], [...VISION, ...NLP, 'multimodal']),
  u('MIT', ['mit', 'massachusetts institute'], [...VISION, 'robotics']),
  u('Carnegie Mellon University', ['carnegie', 'cmu'], [...VISION, ...NLP, 'robotics']),
  u('UC Berkeley', ['berkeley', 'uc berkeley'], [...VISION, ...NLP, 'robotics']),
  u('Georgia Institute of Technology', ['georgia tech', 'gatech'], [...VISION, 'robotics']),
  u('University of Washington', ['washington', 'uw seattle'], [...NLP, ...VISION]),
  u('Cornell University', ['cornell'], [...VISION, 'robotics']),
  u('Princeton University', ['princeton'], [...VISION]),
  u('UCLA', ['ucla', 'los angeles'], [...VISION, ...MED]),
  u('UIUC', ['illinois', 'uiuc'], [...VISION, ...NLP]),
  u('University of Michigan', ['michigan', 'umich'], [...VISION, 'robotics']),
  u('UT Austin', ['texas austin', 'ut austin'], [...VISION, ...NLP]),
  u('Purdue University', ['purdue'], [...VISION, ...ENERGY]),
  u('Columbia University', ['columbia'], [...VISION, ...NLP, ...MED]),
  u('Harvard University', ['harvard'], [...MED, ...VISION]),
  u('Johns Hopkins University', ['johns hopkins', 'hopkins'], [...MED, ...VISION]),
  u('Yale University', ['yale'], [...VISION, ...NLP]),
  u('Duke University', ['duke'], [...MED, ...VISION]),
  u('UW Madison', ['madison', 'wisconsin'], [...NLP, ...VISION]),
  u('NYU', ['nyu', 'new york university'], [...VISION, 'deep learning']),
  u('USC', ['usc', 'southern california'], [...VISION, ...MED]),
  u('Northwestern University', ['northwestern'], [...MED, ...VISION, ...NLP]),
  u('University of Pennsylvania', ['penn', 'upenn'], [...NLP, ...MED]),
  u('Rice University', ['rice'], [...VISION, ...ENERGY]),
  u('Ohio State University', ['ohio state'], [...VISION, ...ENERGY]),
  u('Penn State', ['penn state'], [...VISION, ...ENERGY]),
  u('UC San Diego', ['ucsd', 'san diego'], [...VISION, ...MED]),
  u('UC Irvine', ['uci', 'irvine'], [...VISION, ...MED]),
  u('UC Santa Barbara', ['ucsb', 'santa barbara'], [...VISION]),
  u('UC Davis', ['ucd', 'uc davis'], [...MED, ...VISION]),
  u('UC Riverside', ['ucr', 'riverside'], [...VISION]),
  u('UC Santa Cruz', ['ucsc', 'santa cruz'], [...NLP, ...VISION]),
  u('Northeastern University', ['northeastern'], [...VISION, ...NLP]),
  u('Boston University', ['boston university', 'bu '], [...MED, ...VISION]),
  u('Brown University', ['brown'], [...VISION, ...NLP]),
  u('Caltech', ['caltech'], [...VISION, 'robotics']),
  u('Virginia Tech', ['virginia tech', 'vt '], [...VISION, ...ENERGY]),
  u('University of Virginia', ['virginia', 'uva'], [...VISION]),
  u('NC State', ['nc state', 'north carolina state'], [...VISION, ...ENERGY]),
  u('UNC Chapel Hill', ['unc', 'chapel hill'], [...MED, ...VISION]),
  u('University of Maryland', ['maryland', 'umd'], [...VISION, ...NLP]),
  u('Rutgers University', ['rutgers'], [...VISION, ...NLP]),
  u('Stony Brook University', ['stony brook'], [...VISION, ...MED]),
  u('University at Buffalo', ['buffalo'], [...VISION, ...MED]),
  u('University of Rochester', ['rochester'], [...MED, ...VISION]),
  u('WPI', ['wpi', 'worcester polytechnic'], [...VISION, 'robotics']),
  u('Tufts University', ['tufts'], [...MED, ...VISION]),
  u('Emory University', ['emory'], [...MED, ...VISION]),
  u('Vanderbilt University', ['vanderbilt'], [...MED, ...VISION]),
  u('Notre Dame', ['notre dame'], [...VISION, ...ENERGY]),
  u('Iowa State University', ['iowa state'], [...VISION, ...ENERGY]),
  u('Oregon State University', ['oregon state'], [...VISION, ...ENERGY]),
  u('University of Oregon', ['oregon'], [...NLP, ...VISION]),
  u('University of Utah', ['utah'], [...MED, ...VISION]),
  u('University of Colorado Boulder', ['colorado boulder', 'cu boulder'], [...VISION, ...NLP]),
  u('Colorado State University', ['colorado state'], [...VISION, ...ENERGY]),
  u('University of Arizona', ['arizona', 'uofa'], [...VISION, ...MED]),
  u('Arizona State University', ['arizona state', 'asu'], [...VISION, ...ENERGY]),
  u('University of Florida', ['florida', 'uf '], [...VISION, ...MED]),
  u('University of Miami', ['miami'], [...MED, ...VISION]),
  u('Florida State University', ['florida state', 'fsu'], [...VISION, ...NLP]),
  u('University of Central Florida', ['central florida', 'ucf'], [...VISION]),
  u('University of Tennessee', ['tennessee'], [...VISION, ...ENERGY]),
  u('University of Kentucky', ['kentucky'], [...VISION, ...MED]),
  u('University of Louisville', ['louisville'], [...MED, ...VISION]),
  u('Indiana University', ['indiana', 'iu '], [...NLP, ...VISION]),
  u('University of Iowa', ['iowa'], [...MED, ...VISION]),
  u('University of Minnesota', ['minnesota'], [...VISION, ...MED]),
  u('University of Missouri', ['missouri'], [...VISION, ...MED]),
  u('University of Kansas', ['kansas'], [...VISION, ...ENERGY]),
  u('University of Nebraska', ['nebraska'], [...VISION, ...ENERGY]),
  u('University of Oklahoma', ['oklahoma'], [...VISION, ...ENERGY]),
  u('University of Arkansas', ['arkansas'], [...VISION, ...ENERGY]),
  u('University of Alabama', ['alabama'], [...VISION, ...MED]),
  u('Auburn University', ['auburn'], [...VISION, ...ENERGY]),
  u('Mississippi State University', ['mississippi state'], [...VISION, ...ENERGY]),
  u('Louisiana State University', ['lsu'], [...VISION, ...ENERGY]),
  u('University of Georgia', ['georgia', 'uga'], [...VISION, ...MED]),
  u('Clemson University', ['clemson'], [...VISION, ...ENERGY]),
  u('University of South Carolina', ['south carolina'], [...VISION, ...MED]),
  u('Texas A&M University', ['texas a&m', 'tamu'], [...VISION, ...ENERGY]),
  u('Texas Tech University', ['texas tech'], [...VISION, ...ENERGY]),
  u('Baylor University', ['baylor'], [...MED, ...VISION]),
  u('University of Houston', ['houston'], [...VISION, ...ENERGY]),
  u('University of New Mexico', ['new mexico'], [...VISION, ...ENERGY]),
  u('University of Nevada Reno', ['nevada reno'], [...VISION, ...ENERGY]),
  u('Washington State University', ['washington state', 'wazzu'], [...VISION, ...ENERGY]),
  u('University of Hawaii', ['hawaii'], [...VISION, ...ENERGY]),
  u('University of Delaware', ['delaware'], [...VISION, ...ENERGY]),
  u('Drexel University', ['drexel'], [...MED, ...VISION]),
  u('Lehigh University', ['lehigh'], [...VISION, ...ENERGY]),
  u('Case Western Reserve University', ['case western'], [...MED, ...VISION]),
  u('University of Cincinnati', ['cincinnati'], [...MED, ...VISION]),
  u('Wayne State University', ['wayne state'], [...MED, ...VISION]),
  u('UIC', ['illinois chicago', 'uic'], [...VISION, ...MED]),
  u('Illinois Institute of Technology', ['illinois tech', 'iit'], [...VISION, 'robotics']),
  u('Missouri S&T', ['missouri s&t', 'missouri science'], [...VISION, ...ENERGY]),
  u('Rensselaer Polytechnic Institute', ['rensselaer', 'rpi'], [...VISION, ...ENERGY]),
  u('Binghamton University', ['binghamton'], [...VISION, ...NLP]),
  u('Syracuse University', ['syracuse'], [...VISION, ...NLP]),
  u('Stevens Institute of Technology', ['stevens'], [...VISION, ...ENERGY]),
  u('NJIT', ['njit', 'new jersey institute'], [...VISION, ...ENERGY]),
  u('Temple University', ['temple'], [...MED, ...VISION]),
  u('University of Pittsburgh', ['pitt', 'pittsburgh'], [...MED, ...VISION]),
  u('George Washington University', ['george washington', 'gwu'], [...MED, ...VISION]),
  u('Dartmouth College', ['dartmouth'], [...MED, ...VISION]),
  u('SUNY Albany', ['albany'], [...NLP, ...VISION]),
  u('Kent State University', ['kent state'], [...VISION, ...MED]),
  u('University of Akron', ['akron'], [...VISION, ...ENERGY]),
  u('University of Toledo', ['toledo'], [...MED, ...VISION]),
  u('George Mason University', ['george mason'], [...VISION, ...NLP]),
  u('Virginia Commonwealth University', ['virginia commonwealth', 'vcu'], [...MED, ...VISION]),
  u('West Virginia University', ['west virginia'], [...VISION, ...ENERGY]),
  u('University of Vermont', ['vermont'], [...MED, ...VISION]),
  u('University of New Hampshire', ['new hampshire'], [...VISION, ...ENERGY]),
  u('University of Maine', ['maine'], [...VISION, ...ENERGY]),
  u('University of Rhode Island', ['rhode island'], [...VISION, ...ENERGY]),
  u('University of Connecticut', ['connecticut', 'uconn'], [...VISION, ...MED]),
  u('University of Massachusetts Amherst', ['umass', 'massachusetts amherst'], [...NLP, ...VISION]),
  u('University of Massachusetts Lowell', ['umass lowell'], [...VISION, ...ENERGY]),
  u('Brandeis University', ['brandeis'], [...NLP, ...VISION]),
  u('Clarkson University', ['clarkson'], [...VISION, ...ENERGY]),
  u('Marquette University', ['marquette'], [...MED, ...VISION]),
  u('University of Denver', ['denver'], [...VISION, ...NLP]),
  u('University of Colorado Denver', ['colorado denver'], [...MED, ...VISION]),
  u('Portland State University', ['portland state'], [...VISION, ...ENERGY]),
  u('San Jose State University', ['san jose state'], [...VISION, ...ENERGY]),
  u('San Francisco State University', ['san francisco state'], [...NLP, ...VISION]),
  u('Santa Clara University', ['santa clara'], [...VISION, ...ENERGY]),
  u('University of San Francisco', ['san francisco'], [...NLP, ...VISION]),
  u('Loyola Marymount University', ['loyola marymount'], [...VISION]),
  u('University of Nevada Las Vegas', ['unlv', 'nevada las vegas'], [...VISION]),
  u('Boise State University', ['boise state'], [...VISION, ...ENERGY]),
  u('University of Idaho', ['idaho'], [...VISION, ...ENERGY]),
  u('Montana State University', ['montana state'], [...VISION, ...ENERGY]),
  u('University of Montana', ['montana'], [...VISION, ...ENERGY]),
  u('University of Wyoming', ['wyoming'], [...VISION, ...ENERGY]),
  u('University of North Dakota', ['north dakota'], [...VISION, ...ENERGY]),
  u('University of South Dakota', ['south dakota'], [...VISION, ...ENERGY]),
  u('South Dakota State University', ['south dakota state'], [...VISION, ...ENERGY]),
  u('North Dakota State University', ['north dakota state'], [...VISION, ...ENERGY]),
  u('Kansas State University', ['kansas state'], [...VISION, ...ENERGY]),
  u('Oklahoma State University', ['oklahoma state'], [...VISION, ...ENERGY]),
  u('New Mexico State University', ['new mexico state'], [...VISION, ...ENERGY]),
  u('University of Texas Dallas', ['utd', 'texas dallas'], [...VISION, ...NLP]),
  u('University of Texas Arlington', ['texas arlington', 'uta'], [...VISION, ...ENERGY]),
  u('University of Texas San Antonio', ['texas san antonio', 'utsa'], [...VISION]),
  u('University of Texas El Paso', ['texas el paso', 'utep'], [...VISION, ...ENERGY]),
  u('Southern Methodist University', ['smu'], [...NLP, ...VISION]),
  u('Tulane University', ['tulane'], [...MED, ...VISION]),
  u('LSU Health Sciences', ['lsu health'], [...MED, ...VISION]),
  u('Medical University of South Carolina', ['medical university south carolina'], [...MED, ...VISION]),
  u('Wake Forest University', ['wake forest'], [...MED, ...VISION]),
  u('OHSU', ['ohsu', 'oregon health'], [...MED, ...VISION]),
  u('Oregon Health & Science University', ['oregon health science'], [...MED, ...VISION]),
  u('Mayo Clinic College', ['mayo'], [...MED, ...VISION]),
  u('Cleveland Clinic Lerner', ['cleveland clinic'], [...MED, ...VISION]),
  u('University of Alabama Birmingham', ['uab', 'alabama birmingham'], [...MED, ...VISION]),
  u('University of Texas Southwestern', ['ut southwestern', 'southwestern medical'], [...MED, ...VISION]),
  u('University of Texas Health Houston', ['ut health houston'], [...MED, ...VISION]),
  u('University of Texas Medical Branch', ['utmb', 'medical branch'], [...MED, ...VISION]),
  u('University of Cincinnati Medical', ['cincinnati medical'], [...MED, ...VISION]),
  u('University of Rochester Medical', ['rochester medical'], [...MED, ...VISION]),
  u('SUNY Downstate', ['downstate'], [...MED, ...VISION]),
  u('University of Vermont Medical', ['vermont medical'], [...MED, ...VISION]),
  u('University of Kansas Medical', ['kansas medical'], [...MED, ...VISION]),
  u('University of Nebraska Medical', ['nebraska medical'], [...MED, ...VISION]),
  u('University of Iowa Medical', ['iowa medical'], [...MED, ...VISION]),
  u('University of Wisconsin Medical', ['wisconsin medical'], [...MED, ...VISION]),
  u('University of Illinois Chicago Medical', ['uic medical'], [...MED, ...VISION]),
  u('University of Miami Medical', ['miami medical'], [...MED, ...VISION]),
  u('University of Florida Medical', ['florida medical'], [...MED, ...VISION]),
  u('University of Colorado Anschutz', ['anschutz', 'colorado medical'], [...MED, ...VISION]),
  u('University of Pittsburgh Medical', ['pitt medical'], [...MED, ...VISION]),
  u('University of Maryland Medical', ['maryland medical'], [...MED, ...VISION]),
  u('University of Virginia Medical', ['virginia medical'], [...MED, ...VISION]),
  u('University of North Carolina Medical', ['unc medical'], [...MED, ...VISION]),
  u('University of Michigan Medical', ['michigan medical'], [...MED, ...VISION]),
  u('University of Minnesota Medical', ['minnesota medical'], [...MED, ...VISION]),
  u('University of Washington Medical', ['washington medical'], [...MED, ...VISION]),
  u('University of California San Francisco', ['ucsf'], [...MED, ...VISION]),
  u('University of California Los Angeles Medical', ['ucla medical'], [...MED, ...VISION]),
  u('University of California Davis Medical', ['uc davis medical'], [...MED, ...VISION]),
  u('University of California Irvine Medical', ['uc irvine medical'], [...MED, ...VISION]),
  u('University of California San Diego Medical', ['ucsd medical'], [...MED, ...VISION]),
  u('University of California Riverside Medical', ['ucr medical'], [...MED, ...VISION]),
  u('University of California Santa Barbara Medical', ['ucsb medical'], [...MED, ...VISION]),
  u('University of California Santa Cruz Medical', ['ucsc medical'], [...MED, ...VISION]),
  u('University of California Berkeley Medical', ['uc berkeley medical'], [...MED, ...VISION]),
  u('University of California Merced', ['uc merced', 'merced'], [...VISION, ...ENERGY]),
  u('University of California Hastings', ['hastings'], [...NLP]),
  u('University of California Hastings Law', ['hastings law'], [...NLP]),
];
